---
title: "Lab 5 Intro"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
```

## Setup
1. Go to iclicker.com and record your attendance.
2. Login to the lab computer (please don't use your personal computer).  
3. Navigate to github.com and login.  
4. Find the class repository "datascibiol" (https://github.com/jmledford3115/datascibiol).  
5. Download a copy the class repository to the desktop.  
6. Clone your repository to the desktop.  
7. Copy the files for today's lab from the class repository and paste them into **your** repository.  
8. Open today's lab in RStudio.  

## Agenda
1. Review `select()` and `filter()`.  
2. Learn how to use `filter()` on multiple conditions.  
3. Finish and push homework #4.  
4. Move on to lab #5.  

## Review from last time
### *With a partner, discuss the following questions*
1. What is the association between the tidyverse, dplyr, select, and filter?  
Tidyverse is a library that contains many intuitive packages for statistics
Dplyr is a package in tidyverse, contains filter/select
Select allows you to select components of the data
Filter allows you to filter components of the data

2. Describe how `select ()` can be used to transform data frames.
select allows you to select variables (columns)

3. Describe how `filter ()` can be used to transform data frames. 
Filter allows you to filter out specific values (on the row level), searching across the dataframe


